apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5433 # La porta del servizio del database all'interno del cluster
      targetPort: 5432  # La porta del container del database
  type: LoadBalancer
