apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1 # Puoi regolare il numero di repliche in base alle tue esigenze
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-container
        image: gabri071098/databaseimage:stablelatest # Inserisci il nome dell'immagine del tuo database
        ports:
        - containerPort: 5432 # Porta su cui il database è accessibile all'interno del container
        #env:
        #- name: POSTGRES_DB
        #  value: geofence-emergency
        #- name: POSTGRES_USER
        #  value: postgres
        #- name: POSTGRES_PASSWORD
        #  value: password
        