apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Porta su cui il servizio del frontend sarà accessibile all'interno del cluster
      targetPort: 80 # Porta del frontend all'interno del pod
  type: LoadBalancer # Tipo di servizio per l'accesso esterno (puoi anche usare NodePort o ClusterIP)
