apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: gabri071098/frontendimage:latest 
        ports:
        - containerPort: 80 # Porta su cui il frontend è accessibile all'interno del container
